### ISSUE TITLE
Pinout of PCB components

### ISSUE THREAD

**Issue by dschmag** [Pekaway/ESP32-BLE-WIFI-SHUNT#2]
Hi, 
Is there a schematic or any documentation to find the correct pinout for
- I2C
- ws2812 led
- the buttons

I2C seems to be default, but that depends on the lib you use, I tried GPIO8 (SDA), GPIO9 (SCL), which did NOT work
a schematic would help a lot

I'm currently preparing an esphome config for this device (see https://esphome.io/components/sensor/ina226.html) so also the i2c address would be needed

**Comment by Pekaway** [comment]
HI, 

We are using the Library : #include <INA.h>  // Zanshin INA Library

and changed (Wire.begin (SDA_PIN,SCL_PIN))
-> Wire.begin(7,6);

PIN 12 -  GPIO 6 - SCL
PIN 13  - GPIO 7 - SDA

Pixel LED is connected to PIN 9 - GPIO4

SW1 Boot Switch PIN15 GPIO9
SW2 Chip En PIN 7
Both are pulled up and set to GND by pressing.


Hope that helps. 
Best 
Karl

**Comment by dschmag** [comment]
Thanks, 
works now with esphome in Home Assistant (sensors show up, but I did not test with current etc yet)

![image](https://github.com/user-attachments/assets/4d72d6c9-cc8a-4192-b994-d1a04f63138e)


```

esphome:
  name: pekawayshut
  friendly_name: pekawayshut

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG #VERY_VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "xxxx"

ota:
  - platform: esphome
    password: "xxxx"

wifi:
  networks:
    - ssid: !secret wifi_ssid 
      password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pekawayshut Fallback Hotspot"
    password: "xxx"

captive_portal:

# https://esphome.io/components/i2c#i2c
# not default pins https://github.com/espressif/arduino-esp32/blob/master/variants/esp32c3/pins_arduino.h
i2c:
  sda: GPIO7 
  scl: GPIO6
  scan: true # for debugging

# https://esphome.io/components/sensor/ina226.html
sensor:
  - platform: ina226 # from image name in repo and https://github.com/Pekaway/ESP32-BLE-WIFI-SHUNT/blob/main/docs/ESP32%20Shunt%20V2%20-%20Design%20Notes.pdf
    address: 0x40
    shunt_resistance: 0.000375 ohm # from https://github.com/Pekaway/ESP32-BLE-WIFI-SHUNT/blob/main/Esp32c3_Shunt_BLE_0.1.ino
    max_current: 1022 A # to check
    # adc time used for both, Bus Voltage and Shunt Voltage
    adc_time: 140 us
    adc_averaging: 4
    update_interval: 1s
    current:
      name: "INA226 Current"
    power:
      name: "INA226 Power"
    bus_voltage:
      name: "INA226 Bus Voltage"
    shunt_voltage:
      name: "INA226 Shunt Voltage"

# https://esphome.io/components/light/neopixelbus.html
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO4
    num_leds: 1
    name: "NeoPixel Light"
```
